version: "3"

services:
  fastapi:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  streamlit:
    build: ./app
    command: streamlit run streamlit_app.py --server.port 8001 --server.address 0.0.0.0
    ports:
      - "8001:8001"
    depends_on:
      - fastapi
    networks:
      - mynetwork

networks:
  mynetwork:
