stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - src/data/raw
  data_preprocess:
    cmd: python src/data_preprocess.py
    deps:
    - src/data/raw
    - src/data_preprocess.py
    outs:
    - src/data/processed
    - src/model/process_model
  model_building:
    cmd: python src/model.py
    deps:
    - src/data/processed
    - src/model.py
    outs:
    - src/model/ml_model
    metrics:
    - src/model/log
