stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.val_test_size
    - data_collection.test_size
    outs:
    - data/interim
  data_preprocess:
    cmd: python src/features/data_preprocess.py
    deps:
    - data/interim
    - src/features/data_preprocess.py
    outs:
    - data/processed
    - models/ordinal_encoder.pkl
    - models/one_hot_encoder.pkl
    - models/standardscaler.pkl
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - model_building.lightgbm_model
    - model_building.xgboost_model
    - model_building.catboost_model
    outs:
    - models/lightgbm.pkl
    - models/xgboost.pkl
    - models/catboost.pkl
    - models/ensemble_model.pkl
    metrics:
    - models/logs
  model_evaluation:
    cmd: python src/model/model_eval.py
    deps:
    - data/processed
    - src/model/model_eval.py
    - models
    metrics:
    - reports/metrics.json
