stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  data_preprocess:
    cmd: python src/data_preprocess.py
    deps:
    - data/raw
    - src/data_preprocess.py
    outs:
    - data/processed
    - src/model/process_model
  model_building:
    cmd: python src/model.py
    deps:
    - data/processed
    - src/model.py
    outs:
    - src/model/ml_model
    metrics:
    - src/model/log
  model_evaluation:
    cmd: python src/model_eval.py
    deps:
    - data/processed
    - src/model.py
    - src/model/ml_model
    metrics:
    - src/model/evaluation
