data_collection:
  val_test_size: 0.3
  test_size: 0.5

model_building:
  lightgbm_model:
    colsample_bytree: 0.8
    device: 'gpu'
    learning_rate: 0.05
    n_estimators: 400
    verbosity: -1
    eval_metric: 'rmse'
  xgboost_model:
    colsample_bytree: 0.7
    learning_rate: 0.1
    max_depth: 5
    n_estimators: 500
    eval_metric: 'rmse'
  catboost_model:
    depth: 6
    iterations: 700
    learning_rate: 0.1
    task_type: 'CPU'
    eval_metric: 'RMSE'
